In [5]:
import numpy as np
import matplotlib.pyplot as plt

data = np.genfromtxt('kennlinie_1.csv', delimiter=',', skip_header=8)
print(data)
plt.plot()

[[ 0.00000e+00 -4.47000e-03  5.37779e-01  1.41088e-01]
 [ 1.00000e+00 -4.46000e-03  5.34605e-01  1.41088e-01]
 [ 2.00000e+00 -4.45000e-03  5.29843e-01  1.41088e-01]
 ...
 [ 1.59700e+03  1.15000e-02  5.48888e-01  2.58014e-01]
 [ 1.59800e+03  1.15100e-02  5.52062e-01  2.58014e-01]
 [ 1.59900e+03  1.15200e-02  5.56823e-01  2.58014e-01]]
